### ISSUE TITLE
Unit of measurment of voltage measured

### ISSUE THREAD

**Issue by AlbiBone** [Molorius/ADS126X#11]
This is just a small hint for @Molorius : which is the unit of measurement of the voltage in `readADC1(uint8_t pos_pin,uint8_t neg_pin)`? I do not find in README.md. Can you add this info?
Thanks you a lot for the help!
Regards
A

**Comment by Molorius** [comment]
That is dependent on your reference and gain. 

V<READ> = ADC_VALUE * V<sub>REF</sub> / Gain / 2<sup>31</sup>

Where ADC_VALUE is the value the adc sends after readADC1. 
V<sub>REF</sub> is your reference voltage. The default is a 2.5V internal voltage reference.
Gain is the gain you set it to with the setGain function. 
2<sup>31</sup> is because this is a 32 bit adc (the missing bit shows positive/negative). 

I did not put it in the README because this is how most adcs work.
